### PR TITLE
Renamed `clippy` to `clippy.py`

### PR DESCRIPTION
**Pull request by Mani4D46**
This is to make it clear that the code is written in python.

also I wasn't able to find code of conduct or any set of guidelines, so I suggest adding that too. and also I wasn't able to find any development branches so I also suggesting adding that too

### CODE REVIEW

**Comment by Mani4D46** [comment]
which docstring style is your preferred one? there are [Google Python Style Guide](https://google.github.io/styleguide/pyguide.html), [Sphinx Style Guide](https://pythonhosted.org/an_example_pypi_project/sphinx.html#function-definitions), and [Numpy Style Guide](https://numpydoc.readthedocs.io/en/latest/format.html) or do you like something else?

**Comment by s-atrn** [comment]
Well no, the reason I removed py extension is so that it's better usable with the python shebang. For the branches and coc.. I will make them when there's some real use. Till now it was under basic devpt now its completed so if more and more people participate in it's devpt then i surely will.

**Comment by s-atrn** [comment]
No docstrings style lol I write whatever I want to. Ik I suck at this.

**Comment by Mani4D46** [comment]
> better usable with the python shebang

can you elaborate on that?

**Comment by Mani4D46** [comment]
> No docstrings style

as some say good code is the best documentation but having a docstrings for complex parts of the code is better that not having docstrings

**Pull request closed without merging**
